//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testmgtapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignSubTeacherTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assignSubTeacherTab()
        {
            this.testTabs = new HashSet<testTab>();
        }
    
        public int aId { get; set; }
        public Nullable<int> uId { get; set; }
        public Nullable<int> subId { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual subjectTab subjectTab { get; set; }
        public virtual userTab userTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testTab> testTabs { get; set; }
    }
}
