//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testmgtapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testmgt_newEntities : DbContext
    {
        public testmgt_newEntities()
            : base("name=testmgt_newEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answerTab> answerTabs { get; set; }
        public virtual DbSet<assignSubTeacherTab> assignSubTeacherTabs { get; set; }
        public virtual DbSet<courseTab> courseTabs { get; set; }
        public virtual DbSet<questionTab> questionTabs { get; set; }
        public virtual DbSet<roleTab> roleTabs { get; set; }
        public virtual DbSet<score> scores { get; set; }
        public virtual DbSet<subjectTab> subjectTabs { get; set; }
        public virtual DbSet<testTab> testTabs { get; set; }
        public virtual DbSet<userTab> userTabs { get; set; }
    }
}
