//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testmgtapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public testTab()
        {
            this.questionTabs = new HashSet<questionTab>();
            this.scores = new HashSet<score>();
        }
    
        public int tstId { get; set; }
        public string tstName { get; set; }
        public Nullable<int> cId { get; set; }
        public Nullable<int> subId { get; set; }
        public Nullable<int> aId { get; set; }
    
        public virtual assignSubTeacherTab assignSubTeacherTab { get; set; }
        public virtual courseTab courseTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionTab> questionTabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<score> scores { get; set; }
        public virtual subjectTab subjectTab { get; set; }
    }
}
